//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public System.Guid id_activity { get; set; }
        public System.Guid id_request { get; set; }
        public System.Guid? id_personel { get; set; }
        public string description { get; set; }
        public string result { get; set; }
        public Status status { get; set; }
        public System.DateTime date_reg { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public string act_type { get; set; }
    
        public virtual Activity_Type Activity_Type { get; set; }
    
        public virtual Personel Personel { get; set; }
        
        public virtual Request Request { get; set; }
    }
}
