//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public System.Guid id_client { get; set; }
        public string adress1 { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public System.Guid id_adress { get; set; }

        public string adressString { get { return adress1 +", " + city+ " " + postcode; } }

        public virtual Client Client { get; set; }
    }
}
