//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class System_NaprawEntities : DbContext
    {
        public System_NaprawEntities()
            : base("name=System_NaprawEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Activity_Type> Activity_Type { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Object_Type> Object_Type { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Adress> Adress { get; set; }
    }
}
